"""Regenerate or check repository, KV260 and binary-asset checksums.

Run after staging added/deleted files: git add -A; python scripts/update_manifests.py.
The Git index defines distributed files; restored assets come from the ZIP,
never from local build outputs or freshly generated measurement receipts.
"""

import argparse
import hashlib
import json
from pathlib import Path, PurePosixPath
import subprocess
import zipfile

ROOT = Path(__file__).resolve().parents[1]
ARCHIVE = "assets/binary-evidence.zip"
ASSET_MANIFEST = "assets/manifest.json"
PACKAGE_MANIFEST = "hardware/kv260/PACKAGE_SHA256.json"
REPOSITORY_MANIFEST = "MANIFEST_SHA256.txt"
IGNORE_START = "# BEGIN restored assets (generated by scripts/update_manifests.py)"
IGNORE_END = "# END restored assets"
DERIVED = {ASSET_MANIFEST, PACKAGE_MANIFEST, REPOSITORY_MANIFEST}


def digest(content):
    return hashlib.sha256(content).hexdigest()


def safe_path(name):
    path = PurePosixPath(name)
    if (not name or not path.parts or path.is_absolute() or ".." in path.parts
            or "\\" in name or ":" in path.parts[0]
            or path.as_posix() != name):
        raise ValueError(f"Unsafe archive path: {name}")
    return path


def archive_hashes(root):
    hashes = {}
    with zipfile.ZipFile(root / ARCHIVE) as archive:
        for member in archive.infolist():
            if member.is_dir():
                continue
            safe_path(member.filename)
            if member.filename in hashes:
                raise ValueError(f"Duplicate archive path: {member.filename}")
            if (member.external_attr >> 16) & 0o170000 == 0o120000:
                raise ValueError(f"Archive symlink: {member.filename}")
            hashes[member.filename] = digest(archive.read(member))
    return dict(sorted(hashes.items()))


def distributed_files(root, assets):
    if (root / ".git").exists():
        names = subprocess.check_output(
            ["git", "ls-files", "-z"], cwd=root
        ).decode("utf-8").split("\0")
        return (set(filter(None, names)) | DERIVED) - {REPOSITORY_MANIFEST}
    manifest = root / REPOSITORY_MANIFEST
    if not manifest.is_file():
        raise RuntimeError("A Git checkout or existing release manifest is required")
    names = {line.split("  ", 1)[1] for line in manifest.read_text().splitlines()}
    recorded = json.loads((root / ASSET_MANIFEST).read_text(encoding="utf-8"))
    tracked_assets = set(recorded["tracked_files"])
    return (names - set(assets) | tracked_assets | DERIVED) - {REPOSITORY_MANIFEST}


def json_bytes(data):
    return (json.dumps(data, ensure_ascii=False, indent=2) + "\n").encode("utf-8")


def expected_files(root):
    assets = archive_hashes(root)
    tracked = distributed_files(root, assets)
    forbidden = [name for name in sorted(tracked | set(assets))
                 if name.startswith('figures/') or 'README_TR' in name
                 or name.endswith(('.pdf', '.png', '.svg', '.pptx', '.ipynb', '.m', '.mat'))]
    if forbidden:
        raise ValueError('Files excluded from this distribution: ' + ', '.join(forbidden))
    ignore = (root / ".gitignore").read_text(encoding="utf-8")
    if IGNORE_START in ignore:
        before, tail = ignore.split(IGNORE_START, 1)
        if IGNORE_END not in tail:
            raise ValueError("Incomplete generated ignore block")
        after = tail.split(IGNORE_END, 1)[1]
        ignore = before.rstrip() + "\n" + after.lstrip("\n")
    restored = sorted(set(assets) - tracked)
    ignore = (ignore.rstrip() + "\n\n" + IGNORE_START + "\n"
              + "".join("/" + name + "\n" for name in restored)
              + IGNORE_END + "\n")
    outputs = {".gitignore": ignore.encode("utf-8")}
    outputs[ASSET_MANIFEST] = json_bytes({
        "archive": ARCHIVE,
        "archive_sha256": digest((root / ARCHIVE).read_bytes()),
        "tracked_files": sorted(set(assets) & tracked),
        "files": assets,
    })

    hashes = {}
    for name in sorted(tracked - {PACKAGE_MANIFEST}):
        safe_path(name)
        content = outputs.get(name)
        if content is None:
            path = root / name
            if not path.is_file():
                raise FileNotFoundError(f"Stage file deletions before updating manifests: {name}")
            content = path.read_bytes()
        hashes[name] = digest(content)
    for name, sha in assets.items():
        if name in hashes and hashes[name] != sha:
            raise ValueError(f"Tracked file conflicts with archived asset: {name}")
        hashes[name] = sha

    prefix = "hardware/kv260/"
    package = {name[len(prefix):]: sha for name, sha in sorted(hashes.items())
               if name.startswith(prefix)}
    outputs[PACKAGE_MANIFEST] = json_bytes(package)
    hashes[PACKAGE_MANIFEST] = digest(outputs[PACKAGE_MANIFEST])
    outputs[REPOSITORY_MANIFEST] = "".join(
        f"{sha}  {name}\n" for name, sha in sorted(hashes.items())
    ).encode("utf-8")
    return outputs, len(hashes), len(package), len(assets)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Report stale generated files without changing them")
    args = parser.parse_args()
    outputs, files, package, assets = expected_files(ROOT)
    stale = [name for name, content in outputs.items()
             if not (ROOT / name).is_file() or (ROOT / name).read_bytes() != content]
    if args.check and stale:
        raise SystemExit("Stale manifests/ignore rules: " + ", ".join(stale)
                         + "; run python scripts/update_manifests.py")
    if not args.check:
        for name, content in outputs.items():
            destination = ROOT / name
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(content)
    print(f"PASS: {'checked' if args.check else 'updated'} {files} release files, "
          f"{package} KV260 files and {assets} archived assets")


if __name__ == "__main__":
    main()
