#!/usr/bin/env python3
"""D6 generator: (1) hls_rf/src/rf_forest.h — both router forests of spec.json as constant node tables (leaf votes
pre-normalised exactly as features_ps.forest_predict does: v / max(v.sum(), 1) in float64); (2) hls_rf/tb/rf_tests.bin —
frame result words rebuilt from every <name>_expected.json (recorded and synthetic frames), the float64 reference
features (features_ps == Colab, verified bit-exact on the 30 recorded frames) and the forest verdicts for all 20 sub-frame
rotations, so the C model / HLS csim / silicon can be checked bit for bit.
   python3 golden/generate_forest.py kv260_package/spec.json kv260_package/vectors vectors
"""
import json, glob, os, struct, sys
import numpy as np
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, 'board'))
from features_ps import frontend_features, forest_predict, FE_COLS, N_SUB, K
from rf_ctl import R

N_CLASSES = 5


def flatten_forest(forest):
    """-> roots[T], and per node: f, thr, l, r, leaf flag, leaf_norm[5]; node ids offset per tree."""
    F, THR, L, RR, LEAF, LN = [], [], [], [], [], []      # LEAF[i] = leaf index + 1 (0 = internal); LN indexed by leaf index
    roots = []
    for tree in forest['trees']:
        base = len(F); roots.append(base)
        for nd in tree:
            if 'leaf' in nd:
                v = np.array(nd['leaf'], dtype=float); ln = v / max(v.sum(), 1)
                F.append(0); THR.append(0.0); L.append(0); RR.append(0); LEAF.append(len(LN) + 1); LN.append([float(x) for x in ln])
            else:
                F.append(int(nd['f'])); THR.append(float(nd['thr'])); L.append(base + int(nd['l'])); RR.append(base + int(nd['r'])); LEAF.append(0)
    return roots, F, THR, L, RR, LEAF, LN


def depth(tree, i=0):
    return 0 if 'leaf' in tree[i] else 1 + max(depth(tree, tree[i]['l']), depth(tree, tree[i]['r']))


def emit_header(spec, path):
    out = ['// GENERATED by golden/generate_forest.py from spec.json — the two router forests (scaler folded in), leaf votes pre-normalised.',
           '#pragma once', '#include <stdint.h>']
    names = ['fixed', 'random']
    maxd = 0
    for fi, nm in enumerate(names):
        fo = spec[f'router_forest_{nm}']
        assert fo['classes'] == ['broadband', 'narrowband', 'none', 'pulse', 'sweep']
        roots, F, THR, L, RR, LEAF, LN = flatten_forest(fo)
        d = max(depth(t) for t in fo['trees']); maxd = max(maxd, d)
        T = len(fo['trees']); NN = len(F)
        out.append(f'// forest {fi} = {nm}: {T} trees, {NN} nodes, max depth {d}')
        out.append(f'#define RF{fi}_TREES {T}')
        out.append(f'#define RF{fi}_NODES {NN}')
        out.append(f'static const uint16_t RF{fi}_ROOT[{T}] = {{' + ','.join(map(str, roots)) + '};')
        out.append(f'static const uint8_t  RF{fi}_F[{NN}] = {{' + ','.join(map(str, F)) + '};')
        out.append(f'static const uint16_t RF{fi}_L[{NN}] = {{' + ','.join(map(str, L)) + '};')
        out.append(f'static const uint16_t RF{fi}_R[{NN}] = {{' + ','.join(map(str, RR)) + '};')
        out.append(f'#define RF{fi}_LEAVES {len(LN)}')
        out.append(f'static const uint16_t RF{fi}_LEAF[{NN}] = {{' + ','.join(map(str, LEAF)) + '};')
        out.append(f'static const double   RF{fi}_THR[{NN}] = {{' + ','.join(repr(x) for x in THR) + '};')
        out.append(f'static const double   RF{fi}_LN[{len(LN)}][{N_CLASSES}] = {{' + ','.join('{' + ','.join(repr(x) for x in row) + '}' for row in LN) + '};')
    out.append(f'#define RF_MAX_DEPTH {maxd}')
    out.append(f'#define RF_MAX_TREES {max(len(spec["router_forest_fixed"]["trees"]), len(spec["router_forest_random"]["trees"]))}')
    out.append(f'#define RF_MAX_NODES {max(sum(len(t) for t in spec["router_forest_fixed"]["trees"]), sum(len(t) for t in spec["router_forest_random"]["trees"]))}')
    open(path, 'w').write('\n'.join(out) + '\n')
    print(f'[GEN] {path}: max depth {maxd}')


def words_from_expected(e):
    st = e['spike_stats']; w = [0] * 1024
    w[R['COUNT']] = st['count']; w[R['ISI_N']] = st['isi_n']; w[R['ISI_SUM']] = st['isi_sum']
    w[R['ISI_SQ']] = st['isi_sq_sum'] & 0xFFFFFFFF; w[R['ISI_SQ'] + 1] = st['isi_sq_sum'] >> 32
    w[R['SF_CNT']:R['SF_CNT'] + N_SUB] = st['sf_cnt']; w[R['SF_ISI_SUM']:R['SF_ISI_SUM'] + N_SUB] = st['sf_isi_sum']; w[R['SF_ISI_CNT']:R['SF_ISI_CNT'] + N_SUB] = st['sf_isi_cnt']
    rc = np.array(e['rf_counts'], dtype=np.int64).reshape(-1); w[R['RF_CNT']:R['RF_CNT'] + N_SUB * K] = [int(v) for v in rc]
    return w, int(st['n'])


def rotate_words(w, rot):
    """sub-frame index k -> (k + rot) % N_SUB for the four sub-frame arrays (the hardware does the same)."""
    w2 = list(w)
    for base in (R['SF_CNT'], R['SF_ISI_SUM'], R['SF_ISI_CNT']):
        for k in range(N_SUB): w2[base + k] = w[base + (k + rot) % N_SUB]
    for k in range(N_SUB):
        for b in range(K): w2[R['RF_CNT'] + k * K + b] = w[R['RF_CNT'] + ((k + rot) % N_SUB) * K + b]
    return w2


CLASSES = ['broadband', 'narrowband', 'none', 'pulse', 'sweep']


def emit_tests(spec, vdirs, path):
    recs = []
    for vd in vdirs:
        for f in sorted(glob.glob(os.path.join(vd, '*_expected.json'))):
            if f.endswith('_conv_expected.json'): continue
            e = json.load(open(f)); w, n = words_from_expected(e)
            feats = frontend_features(w, n)
            if e.get('features') is not None:
                assert np.array_equal(np.array(feats), np.array(e['features'])), f'features_ps != expected.json for {f}'
            verd = {}
            for fi, nm in enumerate(['fixed', 'random']):
                fo = spec[f'router_forest_{nm}']
                verd[fi] = [CLASSES.index(forest_predict(fo, frontend_features(rotate_words(w, rot), n))[0]) for rot in range(N_SUB)]
                if e.get('router_verdict') is not None and nm == e.get('protocol'):
                    assert CLASSES[verd[fi][0]] == e['router_verdict'], f'verdict mismatch {f}'
            recs.append((os.path.basename(f).replace('_expected.json', ''), n, w, feats, verd))
    with open(path, 'wb') as fh:
        fh.write(struct.pack('<II', 0x52465453, len(recs)))          # 'RFTS', count
        for name, n, w, feats, verd in recs:
            fh.write(name.encode()[:31].ljust(32, b'\0')); fh.write(struct.pack('<I', n))
            fh.write(struct.pack('<1024I', *[v & 0xFFFFFFFF for v in w]))
            fh.write(struct.pack('<9d', *[float(x) for x in feats]))
            fh.write(struct.pack('<20I', *verd[0])); fh.write(struct.pack('<20I', *verd[1]))
    print(f'[GEN] {path}: {len(recs)} frames')


if __name__ == '__main__':
    spec = json.load(open(sys.argv[1]))
    emit_header(spec, os.path.join(ROOT, 'hls', 'src', 'rf_forest.h'))
    emit_tests(spec, sys.argv[2:], os.path.join(ROOT, 'hls', 'tb', 'rf_tests.bin'))
